### ISSUE TITLE
researchSync not loading

### ISSUE THREAD

**Issue by jmurrayufo** [Danielv123/factorioClusterio#136]
Logs have no reports of the researchSync plugin loading. This seems to have started sometime after the f7f2ce6897c3dc83a5bfa1ad1c2edb2aea1ff387 commit.

**Comment by Danielv123** [comment]
Does `4fed43bad6de0241da22ece40a34c77f84d5b69f` work or is that the one who broke it?

**Comment by Danielv123** [comment]
This is weird. I have heard other people have this problem, but can't seem to reproduce (windows). Will try doing a fresh install. What OS are you on?

**Comment by Danielv123** [comment]
Just reproduced on WSL with node 8. Will try to fix.

**Comment by Danielv123** [comment]
Found the issue, it was a race condition in `./lib/manager/pluginManager.js` getPlugins(). It was checking for the existence of the DISABLED file which disables plugins, but it didn't wait for a response for the last plugin in the list. The reason it worked on my dev setup is because I have a few unreleased plugins, and one of them weren't loading instead.
