### ISSUE TITLE
README.md setup instructions

### ISSUE THREAD

**Issue by fienxjox** [Danielv123/factorioClusterio#21]
Can we increase the level of details / specificity in the README as well as instructions for a Linux install?

**Comment by Danielv123** [comment]
Currently linux installs are not supported, but nodejs is multiplatform so it should work. I might start testing against ubuntu when we near release.

The readme clearly needs more details, I will do some work on it tomorrow. Currently, the problem is that installation IS complicated. I am not sure if anyone but me have gotten it working properly. I am available on Espernet #factorio if you need help with anything specific.

If you manage to make it work, updating the readme would be appreciated.

**Comment by fienxjox** [comment]
I will try to get on Espernet next Friday if possible, I travel for work and the laptop I lug around isn't enough to run Factorio with any base I use and is Windows.

I'm pretty technical in general although not with Factorio or Lua (and I imagine my RCON experience is of limited use since it is for enterprise systems) and would be happy to test against Ubuntu or hybrid systems.
