### ISSUE TITLE
Importing Accumulators with inventoryImports overflows inventory

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#53]
< Odin> Told it to request 100 landfill and 100 accumulator

< Odin> It wouldn't stop- overflowing my inventory and then spewing errors about it

< Odin> but I was out of range of a logi net when this happened

< Odin> It didn't stop trying to till I stopped requesting

< Odin> Just adds a few more and a few more till inv was full

Cause is unknown so far.

**Comment by OdinYggd** [comment]
Another item just experienced the bug. 
Requested 200 concrete, and sure enough it started to add a little more and a little more until my inventory was flooded and I got the in-game alert that my inventory was full. 

I'm using commit a350b39e2fce8d3e94b655d8559a15e1396e3e07 from this repository on Windows 7 64-bit as the slave node with Factorio 0.15.33. 

So far the bug does not seem to happen when requesting circuits, since I've had green and red circuits requesting multiple stacks all day without issue. But if I request accumulators or concrete, it will keep adding the requested amount over and over till my inventory overflows.

**Comment by Danielv123** [comment]
Closing this as not reproducible.
