### ISSUE TITLE
Shared player state (armour/inv)

### ISSUE THREAD

**Issue by admalledd** [Danielv123/factorioClusterio#99]
Allow a player after setting up their power armour etc on one node, to be able to when joining another sync that to them. Possibly other "player" settings too if reasonable like quick-slot filters.

Please, at least some way to not have to configure power armour+legs every time...

**Comment by melwil** [comment]
One of the problems with duplicating inventories across servers is that a player may be able to spend that inventory in multiple servers at once, by logging into multiple.

Since this is a Quality of Life improvement for players, I'd say it could be pretty strict. If you join a server, your entire character object could be marked as "loaded", allowing you to get your entire profile transferred to a new server. Including inventory, armor, weapons, toolbelt setup, and everything else associated with the player.

If you then joined a second server at the same time, you would spawn in, a check for cloud player state would be run, and it would show as already loaded. In that case you get nothing, and the duplication of items is avoided.

One comment which popped up when discussing this on Discord was that players like to visit multiple servers at once. There's legit reasoning for this, since builds are distributed across servers, and being in both builds at once could be quite beneficial. Some way to make that work without violating duplication policy would be nice.

**Comment by Danielv123** [comment]
@melwil above has mentioned most of the reasons why this hasn't been done yet. If someone finds a clever way around that, I would love to integrate it, but I won't have time to work on it for quite a while.

**Comment by Danielv123** [comment]
This issue is now resolved by https://github.com/Danielv123/playerManager.

To get inventory sync, do `node client.js manage shared plugins add https://github.com/Danielv123/playerManager` on both the master and slave.
